### ISSUE TITLE
Probably wrong method called for cancelPrefetchingForItemsAt

### ISSUE THREAD

**Issue by edw4rddx** [kean-docs/kean-docs.github.io#1]
According to the documentation (https://kean-docs.github.io/nuke/documentation/nuke/prefetching)

``` swift
func collectionView(_ collectionView: UICollectionView, cancelPrefetchingForItemsAt indexPaths: [IndexPath]) {
    let urls = indexPaths.map { photos[$0.row] }
    prefetcher.startPrefetching(with: urls)
}
```

Shouldn't we call [stopPrefetching(with:)](https://kean-docs.github.io/nuke/documentation/nuke/imageprefetcher/stopprefetching(with:)-8cdam) here?

Documentation location in the [repository](https://kean-docs.github.io/nuke/data/documentation/nuke/prefetching.json)

**Comment by kean** [comment]
Thanks for the report, fixed.
